### ISSUE TITLE
Pubsec yaml

### ISSUE THREAD

**Issue by devOps-GLC** [GLC-London/GLC-App#6]
- [ ] Change default font to google roboto font family

**Comment by NtemKenyor** [comment]
Please explain, Is this very necessary. Should I go on with it?

**Comment by devOps-GLC** [comment]
> Please explain, Is this very necessary. Should I go on with it?

Yes please do change the default font to roboto

**Comment by NtemKenyor** [comment]
I thought the default font for a Material App is roboto
